.TH "swd_driver_t" 3 "Sat Mar 12 2011" "Version 0.0.1" "libswd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
swd_driver_t \- 
.PP
Interface Driver structure.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <libswd.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "void * \fBdevice\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Interface Driver structure. 

It holds pointer to the driver structure that keeps driver information necessary to work with the physical interface. 

.SH "Author"
.PP 
Generated automatically by Doxygen for libswd from the source code.
