.TH "swd_ahbap_t" 3 "Fri Mar 11 2011" "Version 0.0.1" "libswd" \" -*- nroff -*-
.ad l
.nh
.SH NAME
swd_ahbap_t \- 
.PP
Most actual Advanced High Bandwidth Access Peripherial Bus Reisters.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <libswd.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBack\fP"
.br
.RI "\fILast known state of ACK response. \fP"
.ti -1c
.RI "int \fBcontrolstatus\fP"
.br
.RI "\fILast known CONTROLSTATUS register value. \fP"
.ti -1c
.RI "int \fBtar\fP"
.br
.RI "\fILast known TAR register value. \fP"
.ti -1c
.RI "int \fBdrw\fP"
.br
.RI "\fILast known DRW register value. \fP"
.ti -1c
.RI "int \fBbd0\fP"
.br
.RI "\fILast known BD0 register value. \fP"
.ti -1c
.RI "int \fBbd1\fP"
.br
.RI "\fILast known BD1 register value. \fP"
.ti -1c
.RI "int \fBbd2\fP"
.br
.RI "\fILast known BD2 register value. \fP"
.ti -1c
.RI "int \fBbd3\fP"
.br
.RI "\fILast known BD3 register value. \fP"
.ti -1c
.RI "int \fBdromt\fP"
.br
.RI "\fILast known DROMT register value. \fP"
.ti -1c
.RI "int \fBidr\fP"
.br
.RI "\fILast known IDR register value. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Most actual Advanced High Bandwidth Access Peripherial Bus Reisters. 

.SH "Author"
.PP 
Generated automatically by Doxygen for libswd from the source code.
